# Licensed under the Apache-2.0 license

[package]
name = "mcu-firmware-bundler"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
subst.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
