# Licensed under the Apache-2.0 license

[package]
name = "caliptra-util-host-osal"
version.workspace = true
edition.workspace = true
description = "OS Abstraction Layer for Caliptra Utility Host Library"

[features]
default = ["std"]
std = []
alloc = []