# Licensed under the Apache-2.0 license

[package]
name = "caliptra-util-host-command-types"
version.workspace = true
edition.workspace = true
description = "Shared command types and definitions for Caliptra Utility Host Library"

[dependencies]
zerocopy.workspace = true