# Licensed under the Apache-2.0 license

[platform]
name = "test-flash-based-boot-emulator"
tuple = "riscv32imc-unknown-none-elf"
dynamic_sizing = true
page_size = 256

[platform.rom]
offset = 0x8000_0000
size = 0x2_0000

[platform.itcm]
offset = 0x4000_0000
size = 0x5_0000

[platform.ram]
offset = 0x4005_0000
size = 0x3_0000

[platform.dccm]
offset = 0x5000_0000
size = 0x4000

[platform.flash]
offset = 0x3BFE_0000
size = 0x2_0000

# This section is optional.
# [rom]
# name = "mcu-rom-emulator"
# exec_mem = { "size" = 0x2_0000 } 
# data_mem = { "size" = 0x4000 }
# stack = 0x2e00
# estack = 0x200

[kernel]
name = "mcu-runtime-emulator"
# exec_mem = { "size" = 0x1_d000 }
# data_mem = { "size" = 0x0_9000 }
stack = 0x0_7000

[[app]]
name = "user-app"
# exec_mem = { "size" = 0x3_2000 }
# data_mem = { "size" = 0x1_6800 }
stack = 0xae00

