# Licensed under the Apache-2.0 license

[platform]
tuple = "riscv32imc-unknown-none-elf"
page_size = 256

[platform.rom]
offset = 0x8000_0000
size = 0x2_0000

[platform.itcm]
offset = 0x4000_0000
size = 0x4_6000

[platform.ram]
offset = 0x4004_6000
size = 0x3_a000

[platform.dccm]
offset = 0x5000_0000
size = 0x4000

[platform.flash]
offset = 0x3BFE_0000
size = 0x2_0000

[rom]
name = "mcu-rom-emulator"
exec_mem = { "size" = 0x2_0000 } 
ram = 0x4000
stack = 0x2e00
estack = 0x200

[kernel]
name = "mcu-runtime-emulator"
exec_mem = { "size" = 0x2_0000 }
ram = 0x2_3000
stack = 0x2_22E0

[[app]]
name = "user-app"
exec_mem = { "size" = 0x2_6000 }
ram = 0x1_5000
stack = 0xae00

